name: Dependency Submission

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph-exclude-projects: ':(typed-ids-testing|testing-*)'
        dependency-graph-exclude-configurations: '.*[Tt]est(Compile|Runtime)Classpath'
