name: Run Checks via Gradle on every push

on:
  push:
  pull_request:

jobs:
  gradle:
    strategy:
      matrix:
        java: [21, 22, 23]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary-as-pr-comment: on-failure

      - name: Execute Gradle build
        run: ./gradlew build
